# Generated by Django 4.2.15 on 2024-08-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('pose_x', models.FloatField()),
                ('pose_y', models.FloatField()),
            ],
        ),
    ]
