version: "3.8"

services:
  robot-api:
    build: .
    command: ["/robot-api/entrypoint.sh"]
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - REDIS_URL=${REDIS_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    depends_on:
      - redis
    volumes:
      - .:/robot-api

  redis:
    image: redis:latest
    ports:
      - 6380:6379

networks:
  default:
    name: robot-api-network