version: 1
disable_existing_loggers: False
formatters:
  default:
    format: '%(levelname)s - %(asctime)s - %(module)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
root:
  handlers: [console]
  level: INFO
